hydra:
  job_logging:
    root:
      handlers: [file, console]  # logging to file only.
  run:
    #dir: logs/${dataset}
    dir: attack_logs/corruption/${dataset}

model_type: sdim
dataset: cifar10

data_dir: data

cifar10:
  corruption_data_dir: CIFAR-10-C

cifar100:
  corruption_data_dir: CIFAR-100-C

tiny_imagenet:
  corruption_data_dir: Tiny-Imagenet-C

# model parameters
classifier_name: resnet18  # base classifier
mi_units: 64

cifar10:
  n_classes: 10
  rep_size: 10
  margin: 5

tiny_imagenet:
  n_classes: 200
  rep_size: 200
  margin: 5

# training parameters
n_batch_train: 128
n_batch_test: 200
seed: 1234
device: cuda